<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from /home/seamus/buildkit/build/47-test/web/sites/default/files/civicrm/ext/biz.jmaconsulting.checkavailabletickets/xml/schema/CRM/Checkavailabletickets/EventHoldingTicketsSession.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:21bd1ce4b2496d5cd726a522b808a5d7)
 */

/**
 * Database access object for the EventHoldingTicketsSession entity.
 */
class CRM_Checkavailabletickets_DAO_EventHoldingTicketsSession extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_event_holding_tickets_session';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique EventHoldingTicketsSession ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to Event
   *
   * @var int
   */
  public $event_id;

  /**
   * Column to hold the number of tickets currently being held in this session
   *
   * @var int
   */
  public $number_holding_tickets;

  /**
   * CiviCRM QuickForm Session ID
   *
   * @var string
   */
  public $session_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_event_holding_tickets_session';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'event_id', 'civicrm_event', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Checkavailabletickets_ExtensionUtil::ts('Unique EventHoldingTicketsSession ID'),
          'required' => TRUE,
          'where' => 'civicrm_event_holding_tickets_session.id',
          'table_name' => 'civicrm_event_holding_tickets_session',
          'entity' => 'EventHoldingTicketsSession',
          'bao' => 'CRM_Checkavailabletickets_DAO_EventHoldingTicketsSession',
          'localizable' => 0,
        ],
        'event_id' => [
          'name' => 'event_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Checkavailabletickets_ExtensionUtil::ts('FK to Event'),
          'where' => 'civicrm_event_holding_tickets_session.event_id',
          'table_name' => 'civicrm_event_holding_tickets_session',
          'entity' => 'EventHoldingTicketsSession',
          'bao' => 'CRM_Checkavailabletickets_DAO_EventHoldingTicketsSession',
          'localizable' => 0,
          'FKClassName' => 'CRM_Event_DAO_Event',
        ],
        'number_holding_tickets' => [
          'name' => 'number_holding_tickets',
          'type' => CRM_Utils_Type::T_INT,
          'title' => CRM_Checkavailabletickets_ExtensionUtil::ts('Number Holding Tickets'),
          'description' => CRM_Checkavailabletickets_ExtensionUtil::ts('Column to hold the number of tickets currently being held in this session'),
          'where' => 'civicrm_event_holding_tickets_session.number_holding_tickets',
          'table_name' => 'civicrm_event_holding_tickets_session',
          'entity' => 'EventHoldingTicketsSession',
          'bao' => 'CRM_Checkavailabletickets_DAO_EventHoldingTicketsSession',
          'localizable' => 0,
        ],
        'session_id' => [
          'name' => 'session_id',
          'type' => CRM_Utils_Type::T_STRING,
          'description' => CRM_Checkavailabletickets_ExtensionUtil::ts('CiviCRM QuickForm Session ID'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_event_holding_tickets_session.session_id',
          'table_name' => 'civicrm_event_holding_tickets_session',
          'entity' => 'EventHoldingTicketsSession',
          'bao' => 'CRM_Checkavailabletickets_DAO_EventHoldingTicketsSession',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'event_holding_tickets_session', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'event_holding_tickets_session', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'UI_event_id_session_id' => [
        'name' => 'UI_event_id_session_id',
        'field' => [
          0 => 'event_id',
          1 => 'session_id',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_event_holding_tickets_session::1::event_id::session_id',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
