-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--


-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_event_holding_tickets_session`;
DROP TABLE IF EXISTS `civicrm_event_holding_tickets`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_event_holding_tickets
-- *
-- * Table to hold a count of the number of tickets currently being held
-- *
-- *******************************************************/
CREATE TABLE `civicrm_event_holding_tickets` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique EventHoldingTickets ID',
     `event_id` int unsigned    COMMENT 'FK to CiviCRM Event',
     `number_holding_tickets` int    COMMENT 'Column to hold the number of tickets currently in transaction' 
,
        PRIMARY KEY (`id`)
 
    ,     UNIQUE INDEX `UI_event_id`(
        event_id
  )
  
,          CONSTRAINT FK_civicrm_event_holding_tickets_event_id FOREIGN KEY (`event_id`) REFERENCES `civicrm_event`(`id`) ON DELETE CASCADE  
)    ;

-- /*******************************************************
-- *
-- * civicrm_event_holding_tickets_session
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_event_holding_tickets_session` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique EventHoldingTicketsSession ID',
     `event_id` int unsigned    COMMENT 'FK to Event',
     `number_holding_tickets` int    COMMENT 'Column to hold the number of tickets currently being held in this session',
     `session_id` varchar(255) NOT NULL   COMMENT 'CiviCRM QuickForm Session ID' 
,
        PRIMARY KEY (`id`)
 
    ,     UNIQUE INDEX `UI_event_id_session_id`(
        event_id
      , session_id
  )
  
,          CONSTRAINT FK_civicrm_event_holding_tickets_session_event_id FOREIGN KEY (`event_id`) REFERENCES `civicrm_event`(`id`) ON DELETE CASCADE  
)    ;

 
